### ISSUE TITLE
Feature request: Have Food Planner show base ingredients rather than intermediate

### ISSUE THREAD

**Issue by saspelund** [kirilloid/valheim#3]
Another incredible tool that is going to help my game play so much!

As a feature request that may be quite involved, would it be possible to break down the intermediate ingredients of food items? E.g. Misthare supreme requires Uncooked misthare supreme which itself requires Hare meat x1, Jotun puffs x3, and Carrot x2, but the food planner gives the number of Uncooked misthare supreme rather than its constituent ingredients. This would probably get annoying with things such as Lox meat pie which requires Uncooked lox meat pie which requires Barley flour which requires Barley to be milled, but that last step may be foregone given it's a one-to-one ratio.

I recognize that you have transitioned to writing and understand if these can't be implemented. I would be happy to help in any way that I can.

Thank you again for these great tools! 

P.S. Would it be possible to have the tab in the browser show which calculator (e.g. Attack Calculator) is open in the tab? It currently says "Valheim calculators" for each one, but I have several open given they are so useful!

**Comment by kirilloid** [comment]
Hello. I'm really sorry I got to this only now, but I addressed both of your concerns.
Normally food planner tool tracks what is used as deep through the requirements chain as needed
With Misthare supreme the problem was it was missing recipe.
Page title is now taken from the top header element.

Please check the site and consider closing this issue if it's solved.
If you want other stuff to be implemented, better create a new issue (I'll promise, it won't take months).
Also it's better to create separate issues for separate things. E.g. your request would better be two:
- Misthare supreme in food planner
- page titles

**Comment by kirilloid** [comment]
Closing for now as I think it could be considered fixed.

**Comment by saspelund** [comment]
Thank you so much for your upgrades!!
