### ISSUE TITLE
Character editor don't work

### ISSUE THREAD

**Issue by Trapaceiro** [kirilloid/valheim#4]
When saving and replacing the FCH file, the character returns without any modifications, just reset.

Game version: 0.217.38 (n-20)
Reference: http://valheim.kirilloid.ru/player-edit

**Comment by kirilloid** [comment]
Please, contact me on Discord, so I can look at the bug and identify the problem.

**Comment by Trapaceiro** [comment]
I sent a friend request. Sorry for delay.

**Comment by Trapaceiro** [comment]
Hello, these are the steps I followed....

1 - I created a character in my game client with this appearance:
![Captura de tela 2024-04-03 015111](https://github.com/kirilloid/valheim/assets/17458432/85b63bd0-f542-47dd-b8fa-815b52e78289)

2 - Then I moved the file to local storage, selected it from the website already in player edit (http://valheim.kirilloid.ru/player-edit). And I made the following changes:
![Captura de tela 2024-04-03 020400](https://github.com/kirilloid/valheim/assets/17458432/b139a46c-00df-4545-9cbd-49def840de64)

3 - Without modifying any other option, I clicked to save and download the file.

But by replacing the original file which I modified on the website. My character doesn't have the expected changes...
See the screenshot when loading through the game client:
![Captura de tela 2024-04-03 015405](https://github.com/kirilloid/valheim/assets/17458432/dbd162e4-5ffe-403d-868d-aba2fbf703ad)

Note: If I upload the modified file to the website again, it tells me it is modified exactly as I made it. But in the game client, it isn't.

File used to modify: https://file.io/u8QKlXpH6QYG
File returned by the website: https://file.io/jEQIlKLCOM9I

**Comment by kirilloid** [comment]
Oh, it looses its hair styles completely. Seems like saving is working wrong.

**Comment by kirilloid** [comment]
Hello, I have fixed the bug and deployed new version.

The problem was with what I have found previously:
> character creation date is saved incorrectly

Also the tool now can identify and one-click fix previously incorrectly saved files
![image](https://github.com/kirilloid/valheim/assets/296571/c1e1fabe-fe46-4ad5-afe8-31ac1950e24a)

The fix itself:
https://github.com/kirilloid/valheim/commit/1d191e41287432f9b1ee04fbfa5c6bab0912ad59#diff-fc23856ed5214320cdae702b3eb399db91b45f288eb995f13f72cb825574ba76R206
Stupid mistake, but JavaScript uses milliseconds as the base for date-time measurements, unlike seconds in .net

Please, try the new version and consider closing the issue if it's fixed.

**Comment by Trapaceiro** [comment]
Hello, it seems to work perfectly now. Thank you very much for all the tools made available directly on the web.
